---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add 'admin' user to docker group
      user:
        name: admin
        groups: docker
        append: yes

    - name: Ensure docker is enabled and started
      systemd:
        name: docker
        enabled: true
        state: started
